### ISSUE TITLE
SyntaxError: Can't build lexer

### ISSUE THREAD

**Issue by willshen99** [xnuinside/simple-ddl-parser#199]
Tried to run below sample code: 

```
from simple_ddl_parser import DDLParser

parse_results = DDLParser("""create table dev.data_sync_history(
    data_sync_id bigint not null,
    sync_count bigint not null,
    sync_mark timestamp  not  null,
    sync_start timestamp  not null,
    sync_end timestamp  not null,
    message varchar(2000) null,
    primary key (data_sync_id, sync_start)
); """).run()

print(parse_results)
```

Received SyntaxError: Can't build lexer
```
ERROR: /Users/{username}/Library/Python/3.11/lib/python/site-packages/simple_ddl_parser/ddl_parser.py:155: Invalid regular expression for rule 't_AUTOINCREMENT'. global flags not at the start of the expression at position 50
Traceback (most recent call last):
  File "{scriptname}", line 3, in <module>
    parse_results = DDLParser("""create table dev.data_sync_history(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/{username}/Library/Python/3.11/lib/python/site-packages/simple_ddl_parser/parser.py", line 90, in __init__
    self.lexer = lex.lex(object=self, debug=False, debuglog=log)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/{username}/Library/Python/3.11/lib/python/site-packages/ply/lex.py", line 909, in lex
    raise SyntaxError("Can't build lexer")
SyntaxError: Can't build lexer
```

I have simple-ddl-parser==0.30.0 and ply==3.11 installed

**Comment by slurpyb** [comment]
I think it has something to do with 3.11 now enforcing global flags at the start of regex expressions. See https://github.com/python/cpython/issues/91222

**Comment by max-thorpe-sains** [comment]
I also had the very same error when using simple-ddl-parser==0.30.0 and python 3.11.4. Would really love to use this python module, but can't currently.
