### ISSUE TITLE
import error - version 0.11

### ISSUE THREAD

**Issue by nitin-kakkar** [xnuinside/simple-ddl-parser#30]
hi @xnuinside 
Hope you are doing well

i am getting following error while importing simple_ddl_parser. Could you please check

```
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simple_ddl_parser import DDLParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Dev/venv/lib/python3.7/site-packages/simple_ddl_parser/__init__.py", line 1, in <module>
    from simple_ddl_parser.ddl_parser import DDLParser, parse_from_file
  File "/Users/Dev/venv/lib/python3.7/site-packages/simple_ddl_parser/ddl_parser.py", line 3, in <module>
    from simple_ddl_parser.parser import Parser
  File "/Users/Dev/venv/lib/python3.7/site-packages/simple_ddl_parser/parser.py", line 3, in <module>
    from typing import Dict, List, Optional, Tuple, Literal
ImportError: cannot import name 'Literal' from 'typing' (/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

**Comment by xnuinside** [comment]
@nitin-kakkar, dozens of 'sorry; I forgot that Literal only from 3.8 - please check 0.11.1, just released fix

**Comment by nitin-kakkar** [comment]
thanks for quick fix @xnuinside .. really appreciate it.. you can close the issue
